"""GENERATED by scripts/gen_default_ignorable.py -- do not edit by hand.

Unicode 16.0.0 Default_Ignorable_Code_Point (DerivedCoreProperties.txt, sha256
39d35161f2954497f69e08bdb9e701493f476a3d30222de20028feda36c1dabd), merged into sorted, non-overlapping inclusive ranges.
"""

from __future__ import annotations

UNICODE_VERSION = "16.0.0"

DEFAULT_IGNORABLE_RANGES: tuple[tuple[int, int], ...] = (
    (0x00AD, 0x00AD),
    (0x034F, 0x034F),
    (0x061C, 0x061C),
    (0x115F, 0x1160),
    (0x17B4, 0x17B5),
    (0x180B, 0x180F),
    (0x200B, 0x200F),
    (0x202A, 0x202E),
    (0x2060, 0x206F),
    (0x3164, 0x3164),
    (0xFE00, 0xFE0F),
    (0xFEFF, 0xFEFF),
    (0xFFA0, 0xFFA0),
    (0xFFF0, 0xFFF8),
    (0x1BCA0, 0x1BCA3),
    (0x1D173, 0x1D17A),
    (0xE0000, 0xE0FFF),
)
